### ISSUE TITLE
Lab 3 Suggested Edit: Error in main_m1.c

### ISSUE THREAD

**Issue by ccjunk** [byu-cpe/ecen330#17] opened 2022-07-20 18:13 UTC
In the old interval timer lab, you would call intervalTimer_start() after the intervalTimer_reset(). However, in the new milestone, you do not call intervalTimer_start() after the intervalTimer_reset() at line 98. So, either 1. Write a start command under line 98, or 2. Update the .h file to specify that when reload is called, you have to not only call initCountUp or initCountDown, but you need to start the timers again.

**Comment by jgoeders** [comment] 2022-07-20 18:26
Reload shouldn't start or stop the timer, or call the init functions.  It should just set the LOAD bit so that the LOAD register values are put into the counter registers, and then clear the load bit.

At line 98, the timer should already be running.  Calling reload shouldn't change that.  

...so I think the issue is in your code.

**Comment by ccjunk** [comment] 2022-07-22 20:37
The only suggestion I can think to improve clarity after finishing this lab is making it clear that with the reload function, you can raise the bit and immediately lower it the next line. That had not been clear to me. Everything else that I had issues with was either simple programming errors, being rusty on C code, or a misunderstanding of the lab that would have been solved through a introduction to lab 3 in the digital lab or class lecture. Now I don't know how necessary that clarity is, but it's the one thing I can think of.

**Comment by jgoeders** [comment] 2022-08-16 13:45
Fixed in #345603e7

**Closed as completed by jgoeders** 2022-08-16 13:45 UTC
